name: Create GCP VM Instance

on:
  workflow_dispatch:
env:
  GCP_PROJECT_ID: sturdy-yen-432600-k2 #在切换Google账号时需要更改
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }} #在切换Google账号时需要更改
  GCP_VM_ZONE: 'asia-east1-c' #在创建不同 VM 时需要修改
  GCP_VM_NAME: 'instance-tw' #在创建不同 VM 时需要修改
  SERVICE_ACCOUNT: '884185986692-compute@developer.gserviceaccount.com' #在切换Google账号时需要更改,需要在 GCP 中创建 IAM 角色,Ask a project owner to grant you the iam.serviceAccountUser role on the service account
  SNAPSHOT: 'https://www.googleapis.com/compute/v1/projects/sturdy-yen-432600-k2/global/snapshots/snapshot-1'
  DOMAIN: 'onemorething.pp.ua' #用于自动创建一条新的 DNS 记录
  CF_ZONE_ID: 1fa9774064820f53fe1733e37a19f721 #用于自动创建一条新的 DNS 记录
  PORT: 1081 #暂时用不到
  PROXIED: 'false' # 用于自动创建一条新的 DNS 记录，是否开启Cloudflare代理，默认否
  CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }} # 用于自动创建一条新的 DNS 记录，从GitHub Secrets中获取API Token

jobs:
  Create_GCP_VM_Instance:
    runs-on: ubuntu-latest
    steps:
        
    - name: Checkout Repository
      uses: actions/checkout@v2
  
    - name: Authentication
      id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ env.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2.1.0
      with:
        project_id: ${{ env.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true



    - name: Create VM Instance
      id: Create_VM_Instance
      run: |
        gcloud compute instances create ${{env.GCP_VM_NAME}} \
        --project=${{env.GCP_PROJECT_ID}} \
        --zone=${{env.GCP_VM_ZONE}} \
        --machine-type=e2-micro \
        --network-interface=network-tier=PREMIUM,stack-type=IPV4_ONLY,subnet=default \
        --maintenance-policy=MIGRATE \
        --provisioning-model=STANDARD \
        --service-account=${{env.SERVICE_ACCOUNT}} \
        --scopes=https://www.googleapis.com/auth/cloud-platform \
        --tags=rz,cz,http-server,https-server \
        --create-disk=auto-delete=yes,boot=yes,device-name=${{ env.GCP_VM_NAME }},mode=rw,size=10,source-snapshot=${{env.SNAPSHOT}},type=projects/${{env.GCP_PROJECT_ID}}/zones/${{env.GCP_VM_ZONE}}/diskTypes/pd-balanced \
        --labels=goog-ec-src=vm_add-gcloud \
        --reservation-affinity=any

    - name: Get Current VM External IP
      id: get_current_ip
      run: |
        echo "Waiting 10s"
        sleep 10
        CURRENT_IP=$(gcloud compute instances describe ${{ env.GCP_VM_NAME }} --zone=${{ env.GCP_VM_ZONE }} --format='value(networkInterfaces[0].accessConfigs[0].natIP)')
        echo "::set-output name=current_ip::$CURRENT_IP"
        echo "Current IP is $CURRENT_IP"
