name: Update XrayR Config

on:
  workflow_dispatch:
env:
  GCP_PROJECT_ID: infra-falcon-424407-c7 #在切换Google账号时需要更改
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }} #在切换Google账号时需要更改
  GCP_VM_ZONE: 'asia-southeast1-b' #在创建不同 VM 时需要修改
  GCP_VM_NAME: 'instance-sg' #在创建不同 VM 时需要修改
  SERVICE_ACCOUNT: '995680916485-compute@developer.gserviceaccount.com' #在切换Google账号时需要更改,需要在 GCP 中创建 IAM 角色,Ask a project owner to grant you the iam.serviceAccountUser role on the service account
  SNAPSHOT: 'https://www.googleapis.com/compute/v1/projects/infra-falcon-424407-c7/global/snapshots/snapshot-asia'
  DOMAIN: 'nets.pp.ua' #用于自动创建一条新的 DNS 记录
  CF_ZONE_ID: b2fc014bf87f67714afb1b9c10941a2e #用于自动创建一条新的 DNS 记录
  PORT: 1081 #暂时用不到
  PROXIED: 'false' # 用于自动创建一条新的 DNS 记录，是否开启Cloudflare代理，默认否
  CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }} # 用于自动创建一条新的 DNS 记录，从GitHub Secrets中获取API Token

jobs:
  Create_GCP_VM_Instance:
    runs-on: ubuntu-latest
    steps:
        
    - name: Checkout Repository
      uses: actions/checkout@v2
  
    - name: Authentication
      id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ env.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2.1.0
      with:
        project_id: ${{ env.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true


    - name: connect ssh via gcloud shell
      id: connect_ssh
      run: |
        gcloud compute ssh ${{env.GCP_VM_NAME}} --zone=${{env.GCP_VM_ZONE}}
        
